export const LOGIN_SUCCESS       = 'USER/LOGIN_SUCCESS';
export const LOGIN_REQUEST       = 'USER/LOGIN_REQUEST';
export const LOGIN_FAILURE       = 'USER/LOGIN_FAILURE';
export const LOGIN_LOGOUT        = 'USER/LOGIN_LOGOUT';

export const CHANGE_MAKETS_STATUS = 'MAKETS/CHANGE_MAKET_STATUS';
export const MAKETS_SGRID_PAGE_CHANGE_PARAMS = 'MAKETS/MAKETS_SGRID_PAGE_CHANGE_PARAMS';
export const MAKETS_FILTER_CHANGE = 'MAKETS/MAKETS_FILTER_CHANGE';



