export const OPEN_EDIT_TASK_REQUEST    = 'OPEN_EDIT_TASK_REQUEST'
export const OPEN_EDIT_TASK_FAILURE    = 'OPEN_EDIT_TASK_FAILURE'
export const OPEN_EDIT_TASK_SUCCESS    = 'OPEN_EDIT_TASK_SUCCESS'

export const SWITCH_TAB    = 'SWITCH_TAB'

export const OPEN_CARD_MAKET_REQUEST   =  'OPEN_CARD_MAKET_REQUEST'
export const OPEN_CARD_MAKET_FAILURE    = 'OPEN_CARD_MAKET_FAILURE'
export const OPEN_CARD_MAKET_SUCCESS    = 'OPEN_CARD_MAKET_SUCCESS'




