export const OPEN_CARD_MAKET_REQUEST        = 'OPEN_CARD_MAKET_REQUEST'
export const OPEN_CARD_MAKET_FAILURE        = 'OPEN_CARD_MAKET_FAILURE'
export const OPEN_CARD_MAKET_SUCCESS        = 'OPEN_CARD_MAKET_SUCCESS'
export const ADD_TASK                       = 'ADD_TASK'
export const OPEN_EDIT_TASK_REQUEST         = 'OPEN_EDIT_TASK_REQUEST'
export const OPEN_EDIT_TASK_FAILURE         = 'OPEN_EDIT_TASK_FAILURE'
export const OPEN_EDIT_TASK_SUCCESS         = 'OPEN_EDIT_TASK_SUCCESS'
export const CANCEL_TASK_EDITING            = 'CANCEL_TASK_EDITING'
export const SAVE_TASK_REQUEST              = 'SAVE_TASK_REQUEST'
export const SAVE_TASK_FAILURE              = 'SAVE_TASK_FAILURE'
export const SAVE_TASK_SUCCESS              = 'SAVE_TASK_SUCCESS'
export const REMOVE_TASK_START              = 'REMOVE_TASK_START'
export const REMOVE_TASK_CANCEL             = 'REMOVE_TASK_CANCEL'
export const REMOVE_TASK_REQUEST            = 'REMOVE_TASK_REQUEST'
export const REMOVE_TASK_FAILURE            = 'REMOVE_TASK_FAILURE'
export const REMOVE_TASK_SUCCESS            = 'REMOVE_TASK_SUCCESS'
export const REMOVE_TASK_FILE               = 'REMOVE_TASK_FILE'
export const ADD_TASK_FILE                  = 'ADD_TASK_FILE'
export const EDITING_HTML_TEXT              = 'EDITING_HTML_TEXT'
export const SWITCH_TAB                     = 'SWITCH_TAB'
export const DOWNLOAD_FILE_MAKET_REQUEST    = 'DOWNLOAD_FILE_MAKET_REQUEST'
export const DOWNLOAD_FILE_MAKET_FAILURE    = 'DOWNLOAD_FILE_MAKET_FAILURE'
export const DOWNLOAD_FILE_MAKET_SUCCESS    = 'DOWNLOAD_FILE_MAKET_SUCCESS'
export const UPLOAD_FILE_MAKET_REQUEST      = 'UPLOAD_FILE_MAKET_REQUEST'
export const UPLOAD_FILE_MAKET_FAILURE      = 'UPLOAD_FILE_MAKET_FAILURE'
export const UPLOAD_FILE_MAKET_SUCCESS      = 'UPLOAD_FILE_MAKET_SUCCESS'
export const DOWNLOAD_FILE_TASK_REQUEST     = 'DOWNLOAD_FILE_TASK_REQUEST'
export const DOWNLOAD_FILE_TASK_FAILURE     = 'DOWNLOAD_FILE_TASK_SUCCESS'
export const DOWNLOAD_FILE_TASK_SUCCESS     = 'DOWNLOAD_FILE_TASK_SUCCESS'
export const OPEN_FOLDER_FILES_TASK         = 'OPEN_FOLDER_FILES_TASK'
export const SET_MAKET_STATUS_REQUEST       = 'SET_MAKET_STATUS_REQUEST'
export const SET_MAKET_STATUS_FAILURE       = 'SET_MAKET_STATUS_FAILURE'
export const SET_MAKET_STATUS_SUCCESS       = 'SET_MAKET_STATUS_SUCCESS'
export const CLEAR_MESSAGE                  = 'CLEAR_MESSAGE'


export const REPORTS_REQUEST                = 'REPORTS_REQUEST';
export const REPORTS_SUCCESS                = 'REPORTS_SUCCESS';
export const REPORTS_FAILURE                = 'REPORTS_FAILURE';

export const REPORT_REQUEST                = 'REPORT_REQUEST';
export const REPORT_SUCCESS                = 'REPORT_SUCCESS';
export const REPORT_FAILURE                = 'REPORT_FAILURE';

export const OPEN_FOLDER_REPORT             = 'OPEN_FOLDER_REPORT'



